<?php

namespace AppBundle\Entity;

/**
 * PlannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlannerRepository extends \Doctrine\ORM\EntityRepository
{
}
