<?php

namespace AppBundle\Entity;

/**
 * RelationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RelationsRepository extends \Doctrine\ORM\EntityRepository
{
}
